# general
config_name: "config_d03"
h5_path: "data_logging/demo/sample_dance+t=2023-10-09-17-37-58/data+seq_name=sample_dance.h5"
seq_length: 2

# forces:
force_specs:
  tau_opt: 1.0

# estimation
estimation_specs:
  predict_M_inv: True
  num_train_steps: 4000
  loss:
    name: "impulse_loss"
  optimizer:
    name: "Adam"
    params:
      learning_rate: 2.5e-4
      amsgrad: True
  batch_size: 64
  steps_til_val: 100
  models:
    CRBA:
      arch: "nn"
      network: "CRBA"
      urdf_path: "URDF/manual.urdf"
    nn+SymmNet:
      network: "SymmNetQVel"
      mlp:
        depth: 8
      activation: "lrelu"
      normalize_inputs: False
    nn+UnconNet:
      arch: "nn"
      network: "UnconNetQVel"
      mlp:
        depth: 8
      activation: "lrelu"
      normalize_inputs: False
    nn+SPDNet+Eig+ReLU:
      arch: "nn"
      network: "SPDNetQVel"
      mlp:
        depth: 8
      spd_layer:
        type: "eigen"
        min_value: 1.0e-10
        positivity: "ReLU"
      activation: "lrelu"
      normalize_inputs: False
    nn+SPDNet+Eig+Softplus:
      arch: "nn"
      network: "SPDNetQVel"
      mlp:
        depth: 8
      spd_layer:
        type: "eigen"
        min_value: 1.0e-10
        positivity: "Softplus"
      activation: "lrelu"
      normalize_inputs: False
    nn+SPDNet+Eig+Exp:
      arch: "nn"
      network: "SPDNetQVel"
      mlp:
        depth: 8
      spd_layer:
        type: "eigen"
        min_value: 1.0e-10
        positivity: "Exp"
      activation: "lrelu"
      normalize_inputs: False
    nn+SPDNet+Eig+Abs:
      arch: "nn"
      network: "SPDNetQVel"
      mlp:
        depth: 8
      spd_layer:
        type: "eigen"
        min_value: 1.0e-10
        positivity: "Abs"
      activation: "lrelu"
      normalize_inputs: False

# visualization
visual_specs:
  plot_dir: "plots/"
  tb_dir: "tb/"

# data saving
data_save_specs:
  data_save_dir: "data_logging/"