# general
config_name: "config_e05"
# h5_path: "data_logging/demo/sample_dance+t=2023-10-10-15-03-25/data+seq_name=sample_dance.h5"
h5_path: "data_logging/demo/sample_dance+t=2023-10-11-12-52-04/data+seq_name=sample_dance.h5"
seq_length: 2

# data use:
data_use:
  use_per_cycle_data: True
  force_terms:
    tau: 1.0

# estimation
estimation_specs:
  predict_M_inv: True
  num_train_steps: 10000
  loss:
    name: "velocity_loss"
  optimizer:
    name: "Adam"
    params:
      learning_rate: 2.5e-4
      amsgrad: True
  batch_size: 1024
  steps_til_val: 100
  models:
    # nn+SymmNet:
    #   network: "SymmNetQVel"
    #   mlp:
    #     depth: 8
    #   activation: "lrelu"
    #   normalize_inputs: False
    # nn+UnconNet:
    #   arch: "nn"
    #   network: "UnconNetQVel"
    #   mlp:
    #     depth: 8
    #   activation: "lrelu"
    #   normalize_inputs: False
    nn+SPDNet+Eig+ReLU:
      arch: "nn"
      network: "SPDNetBase"
      mlp:
        depth: 8
      spd_layer:
        type: "eigen"
        min_value: 1.0e-10
        positivity: "ReLU"
      activation: "lrelu"
      normalize_inputs: False
    CRBA:
      arch: "nn"
      network: "CRBA"
      urdf_path: "URDF/manual.urdf"

# visualization
visual_specs:
  plot_dir: "plots/"
  tb_dir: "tb/"

# data saving
data_save_specs:
  data_save_dir: "data_logging/"