# general
config_name: "config_a01"
h5_path: "data_logging/demo/sample_dance+t=2023-10-07-15-29-33/data+seq_name=sample_dance.h5"
seq_length: 5

# forces:
force_specs:
  tau_opt: 1.0

# estimation
estimation_specs:
  num_train_steps: 2000
  optimizer:
    name: "Adam"
    params:
      learning_rate: 5.0e-4
      amsgrad: False
  batch_size: 32
  steps_til_val: 100
  models:
    nn+SPDNet+Eig+ReLU:
      arch: "nn"
      network: "SPDNetQVel"
      mlp:
        depth: 8
      spd_layer:
        type: "eigen"
        min_value: 1.0e-10
        positivity: "ReLU"
      activation: "lrelu"
      normalize_inputs: False
    nn+SymmNet:
      network: "SymmNetQVel"
      mlp:
        depth: 8
      activation: "lrelu"
      normalize_inputs: False
    nn+UnconNet:
      arch: "nn"
      network: "UnconNetQVel"
      mlp:
        depth: 8
      activation: "lrelu"
      normalize_inputs: False

# visualization
visual_specs:
  plot_dir: "plots/"
  tb_dir: "tb/"