# general
config_name: "config_testing"
h5_path: "data_logging/demo/sample_dance+t=2023-10-11-12-52-04/data+seq_name=sample_dance.h5"
pretrained_nw_path: "trained_models/"
seq_length: 10
temporal_window: 1

# dynamics:
dynamics:
  delta_t: 0.011
  num_dyn_cycles: 6
  con_thresh: 1.0e-3
  tau_limit: 80.0
  humanoid_urdf_path: "URDF/manual.urdf"

# kinematics:
kinematics:
  img_width: 1280
  img_height: 720
  speed_limit: 15.0
  2d_joint_pos_path: "sample_data/sample_dance.npy"
  floor_known: True
  floor_position_path: "sample_data/sample_floor_position.npy"
  cam_params_known: True
  cam_params_path: "sample_data/sample_cam_params.npy"

# inertia estimation
inertia_estimate:
  predict_M_inv: False
  num_train_steps: 200
  loss:
    name: "mae_loss"
  optimizer:
    name: "Adam"
    params:
      learning_rate: 2.5e-4
      amsgrad: True
  batch_size: 1
  steps_til_val: 10
  models:
    # nn+SymmNet:
    #   network: "SymmNetQVel"
    #   mlp:
    #     depth: 8
    #   activation: "lrelu"
    #   normalize_inputs: False
    # nn+UnconNet:
    #   arch: "nn"
    #   network: "UnconNetQVel"
    #   mlp:
    #     depth: 8
    #   activation: "lrelu"
    #   normalize_inputs: False
    nn+SPDNet+Eig+ReLU:
      arch: "nn"
      network: "SPDNetQVel"
      mlp:
        depth: 8
      spd_layer:
        type: "eigen"
        min_value: 1.0e-10
        positivity: "ReLU"
      activation: "lrelu"
      normalize_inputs: False
    CRBA:
      arch: "nn"
      network: "CRBA"
      urdf_path: "URDF/manual.urdf"

# visualization
visual_specs:
  plot_dir: "plots/"
  tb_dir: "tb/"

# data saving
data_save_specs:
  data_save_dir: "data_logging/"