# general
config_name: "config_testing"
h5_path: "results/sample_dance+t=2023-10-07-15-29-33/data+seq_name=sample_dance.h5"
seq_length: 2

# estimation
estimation_specs:
  num_train_steps: 10
  optimizer:
    name: "Adam"
    params:
      learning_rate: 2.5e-4
      amsgrad: True
  batch_size: 64
  steps_til_val: 100
  models:
    CRBA:
      arch: "nn"
      network: "CRBA"
      urdf_path: "URDF/manual.urdf"
    nn+SymmNet:
      network: "SymmNetQVel"
      mlp:
        depth: 8
      activation: "lrelu"
      normalize_inputs: False
    nn+UnconNet:
      arch: "nn"
      network: "UnconNetQVel"
      mlp:
        depth: 8
      activation: "lrelu"
      normalize_inputs: False
    nn+SPDNet+Eig+ReLU:
      arch: "nn"
      network: "SPDNetQVel"
      mlp:
        depth: 8
      spd_layer:
        type: "eigen"
        min_value: 1.0e-10
        positivity: "ReLU"
      activation: "lrelu"
      normalize_inputs: False

# visualization
visual_specs:
  plot_dir: "plots/"
  tb_dir: "tb/"