# general
config_name: "config_a04"
h5_path: "results/sample_dance+t=2023-10-05-21-39-09/data+seq_name=sample_dance.h5"
seq_length: 5

# estimation
estimation_specs:
  num_train_steps: 2000
  learning_rate: 5.0e-4
  batch_size: 32
  steps_til_val: 100
  models:
    crba:
      arch: "nn"
      network: "CRBA"
    nn+SymmNet:
      network: "SymmNetQVel"
      mlp:
        depth: 8
      activation: "lrelu"
      normalize_inputs: False
    nn+UnconNet:
      arch: "nn"
      network: "UnconNetQVel"
      mlp:
        depth: 8
      activation: "lrelu"
      normalize_inputs: False
    nn+SPDNet+Eig+ReLU:
      arch: "nn"
      network: "SPDNetQVel"
      mlp:
        depth: 8
      spd_layer:
        type: "eigen"
        min_value: 1.0e-4
        positivity: "ReLU"
      activation: "lrelu"
      normalize_inputs: False
    nn+SPDNet+Eig+Softplus:
      arch: "nn"
      network: "SPDNetQVel"
      mlp:
        depth: 8
      spd_layer:
        type: "eigen"
        min_value: 1.0e-4
        positivity: "Softplus"
      activation: "lrelu"
      normalize_inputs: False
    nn+SPDNet+Eig+Exp:
      arch: "nn"
      network: "SPDNetQVel"
      mlp:
        depth: 8
      spd_layer:
        type: "eigen"
        min_value: 1.0e-4
        positivity: "Exp"
      activation: "lrelu"
      normalize_inputs: False
    nn+SPDNet+Eig+Abs:
      arch: "nn"
      network: "SPDNetQVel"
      mlp:
        depth: 8
      spd_layer:
        type: "eigen"
        min_value: 1.0e-4
        positivity: "Abs"
      activation: "lrelu"
      normalize_inputs: False

# visualization
visual_specs:
  plot_dir: "plots/"
  tb_dir: "tb/"